CREATE TABLE IF NOT EXISTS page_meta (
  id INT AUTO_INCREMENT PRIMARY KEY,
  page_path VARCHAR(255) NOT NULL UNIQUE,
  meta_title VARCHAR(200) DEFAULT NULL,
  meta_description VARCHAR(320) DEFAULT NULL,
  og_image VARCHAR(500) DEFAULT NULL,
  schema_markup JSON DEFAULT NULL,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  created_by INT DEFAULT NULL,
  INDEX idx_page_path (page_path),
  FOREIGN KEY (created_by) REFERENCES users(id) ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
